### PR TITLE
Add authorise3ds2 endpoint

### PR DESCRIPTION
**Pull request by crrood**
From https://github.com/Adyen/adyen-ruby-api-library/issues/19

### CODE REVIEW

**Comment by crrood** [comment]
Hey @rikterbeek - can you or someone on your team approve this request?

**Comment by davidbasalla** [comment]
Has there been any update on this PR? We'd love to make use of this functionality

**Comment by crrood** [comment]
Hi David,

While we wait for approval on the release, you can use the develop branch.  There are no substantive changes in the other 2 commits, just some error reporting and gemspec updates.

**Comment by rikterbeek** [comment]
@crrood next time just add me as reviewer then it will be on my list to review.

**Pull request merged**
