### PR TITLE
Add adapter_options to client

### PR DESCRIPTION
**Pull request by ollym**
For use with a custom Faraday adapter

### CODE REVIEW

**Comment by wboereboom** [comment]
Hi @ollym,

Thanks for contributing.
Could you add a test to the client spec to verify validity?
LGTM otherwise!

Kind Regards,
Wouter
Adyen

**Comment by ollym** [comment]
@wboereboom how do you want to do it? There's even no tests for `adapter` currently

**Comment by ollym** [comment]
@wboereboom ?

**Comment by jillingk** [comment]
Quickly resolved conflicts, we can safely merge this imo.

**Pull request merged**
