### PR TITLE
Update response

### PR DESCRIPTION
**Pull request by hbkwong**
Update response from Faraday object to standard AdyenResult object (w/ parsed JSON). Add functionality for Ruby hash access/edit via dot notation.

### CODE REVIEW

**Comment by crrood** [comment]
Looks good to me

**Comment by AlexandrosMor** [comment]
Hello @hbkwong,
Can you please resolve the conflicts?
regard,

**Comment by hbkwong** [comment]
Sounds good! Changed to `4.0.0` (from `3.0.1`) in version.rb, and fix some comments in other files

**Comment by rikterbeek** [comment]
@crrood can you merge and do a new release thanks.

**Pull request merged**
