### PR TITLE
Update checkout to v49 and library version 2.0.1

### PR DESCRIPTION
**Pull request by fconforti**

### CODE REVIEW

**Comment by crrood** [comment]
Hey fconforti,

Thanks for submitting this, it's been on my list for a couple weeks now.  Can you also update the versions in the other services to match the most recent from the Adyen docs?

- Colin

**Comment by fconforti** [comment]
Sure, Colin

I'll do that right now.

Thanks,
-Filippo

**Comment by crrood** [comment]
Hey Filippo,

Looks great, thanks!

- Colin

**Comment by fconforti** [comment]
Thank you, Colin!

Cheers,
F.

**Comment by x4d3** [comment]
@fconforti @crrood Do we know when will have the next release of the gem ? 

THank you

**Comment by crrood** [comment]
Hi Xavier,

I've requested to merge the outstanding changes into master.

Note that you can change versions using the client object, for instance:
adyen.checkout.version = 50

-Colin

**Comment by x4d3** [comment]
Thanks, but I need the latest version to be able to call `authorise3ds2`
I like to avoid relying on the github commit and to use the properly released gem version.

**Pull request merged**
